name: Affected Code Owners
description: GitHub Action to determine which `CODEOWNERS` are affected based on changes in a pull request.

branding:
  icon: 'users'
  color: green

inputs:
  token:
    description: 'The GitHub token used to perform git operations'
    default: ${{ github.token }}

outputs:
  individual-owners:
    description: >
      A JSON-formatted string containing a deduplicated array of all affected code owners for the changed files.
      Example:
        ["@owner1", "@owner3", "@owner2"]

  grouped-owners:
    description: >
      A JSON-formatted string containing a deduplicated array of owner groups, where each group corresponds to a specific rule that matched the changed files.
      Each group contains an array of owners.
      Example:
        [
          ["@owner1", "@owner3"],
          ["@owner2", "@owner3"]
        ]

runs:
  using: node20
  main: dist/index.js
